{% set name = "paracelsus" %}
{% set version = "0.8.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/paracelsus-{{ version }}.tar.gz
  sha256: 0a2935cf2f1e1e91d478842e886bfeb4680c51c1db17de876490848e4f1862cb

build:
  entry_points:
    - paracelsus = paracelsus.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=67.0
    - setuptools-scm >=7.1
    - pip
  run:
    - python >={{ python_min }}
    - pydot
    - sqlalchemy
    - typer
    - toml

test:
  imports:
    - paracelsus
  commands:
    - pip check
    - paracelsus --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tedivm/paracelsus
  summary: Visualize SQLAlchemy Databases using Mermaid or Dot Diagrams.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
