{% set name = "paracelsus" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/paracelsus-{{ version }}.tar.gz
  sha256: 7ac7c2cfbea0d263ea624c461358d41bfa800e8c34ba92c0ef9c5d0401af44ac

build:
  entry_points:
    - paracelsus = paracelsus.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=67.0
    - setuptools-scm >=7.1
    - pip
  run:
    - python >=3.7
    - pydot
    - sqlalchemy
    - typer

test:
  imports:
    - paracelsus
  commands:
    - pip check
    - paracelsus --help
  requires:
    - pip

about:
  home: https://github.com/tedivm/paracelsus
  summary: Visualize SQLAlchemy Databases using Mermaid or Dot Diagrams.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
