{% set name = "paracelsus" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/paracelsus-{{ version }}.tar.gz
  sha256: b53ee3d70a7e5cea45db895dc44b568bf44c769f3ca721a596a4f1caff27af63

build:
  entry_points:
    - paracelsus = paracelsus.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools >=67.0
    - setuptools-scm >=7.1
    - pip
  run:
    - python >=3.10
    - pydot
    - sqlalchemy
    - typer
    - toml

test:
  imports:
    - paracelsus
  commands:
    - pip check
    - paracelsus --help
  requires:
    - pip

about:
  home: https://github.com/tedivm/paracelsus
  summary: Visualize SQLAlchemy Databases using Mermaid or Dot Diagrams.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
