schema_version: 1

context:
  name: paracelsus
  version: "0.13.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/paracelsus-${{ version }}.tar.gz
  sha256: e347edd8718f9ebc8a13f55a985547896d9f18b3d048fd881b34b03a1bc73184

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - paracelsus = paracelsus.cli:app

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=67.0
    - setuptools-scm >=7.1
    - pip
  run:
    - python >=${{ python_min }}
    - pydot <4.0
    - sqlalchemy
    - typer
    - toml

tests:
  - python:
      imports:
        - paracelsus
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}
    script:
      - paracelsus --help

about:
  summary: Visualize SQLAlchemy Databases using Mermaid or Dot Diagrams.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/tedivm/paracelsus

extra:
  recipe-maintainers:
    - thewchan
